# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template tests the deployed function and executes it. It should fail to complete in time and not timeout.
Resources:
  Test1Execution:
    Type: Custom::HelloWorld
    Properties:
      ServiceToken: !ImportValue ST-Function
      Test: Unredacted
      Example: Unredacted
      Custom: Unredacted
      DeleteMe: Unredacted
      DeleteMeExtended: Unredacted
      Unredacted: Unredacted
  Test2Execution:
    Type: Custom::Test
    Properties:
      ServiceToken: !ImportValue ST-Function
      Test: Unredacted
      Example: Unredacted
      Custom: Unredacted
      DeleteMe: Unredacted
      DeleteMeExtended: Unredacted
      Unredacted: Unredacted
